name: Parse Issue to Markdown File
on:
  issues:
    types: [opened, edited]

permissions:
  contents: write

jobs:
  parse-issue-to-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run script to create markdown file
        id: parser
        run: |
          node scripts/parse-issue-to-news.js
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          ARTICLES_DIR: Writing

      - name: Discover created markdown file
        id: discover
        shell: bash
        run: |
          set -euo pipefail
          dir="Writing"
          fname=$(ls -1t "$dir"/*.md 2>/dev/null | head -n1 | xargs -n1 basename || true)
          if [ -z "${fname:-}" ]; then
            echo "No markdown file found under $dir/" >&2
            exit 1
          fi
          echo "filename=${fname}" >> "$GITHUB_OUTPUT"

      - name: Commit and push the new markdown file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add Writing/${{ steps.discover.outputs.filename }}
          git commit -m "docs: add new article from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push origin HEAD:main
